### ISSUE TITLE
use chanserv TOPIC command to set the topic

### ISSUE THREAD

**Issue by floatingatoll** [rtucker-mozilla/mozilla-nagios-bot#47]
When multiple bots are present in one channel, they all try to set the topic. If they all succeed, it spams the channel with noise. If only one of them has +h/o access to set the topic, then that bot can never fail or the topic is not set.

Using the chanserv TOPIC command resolves this, as ChanServ silently ignores duplicate TOPIC commands, setting the topic precisely once and discarding the remainder from the bots.

**Comment by rtucker-mozilla** [comment]
The issue we've seen is timing, where the bots fight over setting the topic between the current and the new (proper) to be updated topic. Due to the splay difference of the bots updating themselves, the back/forth can go on for quite a while. It's possible that I'm missing something here with the chanserv topic command fix though.

**Comment by floatingatoll** [comment]
Ah, this only works if the bots set the topic at startup and *not* any
other time. Otherwise, this isn't effective. :(

**Comment by rtucker-mozilla** [comment]
per conversation, this doesn't seem possible
